# Generated by Django 4.2 on 2023-04-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_author_post_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='overview',
            new_name='descripcion',
        ),
    ]
