# Generated by Django 4.2 on 2023-04-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_title_category_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
